site:
  title: ProductDock documentation
  start_page: docs-en:ROOT:index.adoc   # start page EN

content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs-en
  - url: .
    branches: HEAD
    start_path: docs-sr
  - url: .
    branches: HEAD
    start_path: docs-assets

ui:
  bundle:
    url: https://antora-ui-productdock-bef695.gitlab.io/ui/v1.0.8Q/ui-bundle.zip
    snapshot: false

output:
  dir: public