site:
  title: ProductDock documentation
  start_page: docs-en:ROOT:index.adoc   # start page EN

content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs-en
  - url: .
    branches: HEAD
    start_path: docs-sr

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: public